### ISSUE TITLE
Notebook cannot be opened

### ISSUE THREAD

**Issue by jjanousek** [emilio1993/WatsonMachineLearningGuide#1]
Hi,

I have run into an issue with the IRIS_MODEL_DEPLOYMENT.ipynb notebook.

After downloading the IRIS_MODEL_DEPLOYMENT.ipynb file I try to open it with jupyter lab (version 1.1.4) which leads to 2 responses:

File "IRIS_MODEL_DEPLOYMENT.ipynb" has unsaved changes, close without saving?

(Here clicking either Cancel or Okay does not make a difference)

After Which I get:

Unreadable Notebook: /Users/johannes/test_space/depl/ibm/IRIS_MODEL_DEPLOYMENT.ipynb NotJSONError("Notebook does not appear to be JSON: '\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang...")

Maybe changes to the notebook were not saved correctly before uploading it to github?

**Comment by emigolaso** [comment]
Hello @jjanousek , 

Thanks for the feedback. The file has been re uploaded. 

Please clone the repository or download the **full zip file**. Let me know if that works and we can update the instructions accordingly. 

<img width="360" alt="Screen Shot 2021-01-25 at 6 54 42 AM" src="https://user-images.githubusercontent.com/53913862/105703213-e3a42900-5eda-11eb-995e-04e7a679eb30.png">

**Comment by jjanousek** [comment]
Hi Emilio,

works fine now.

thanks, Johannes
